
name = "wp-nexus-api"
main = "serverless/worker.ts"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

[vars]
# De centrale database URL voor WP-Nexus Pro
DB_URL = "postgres://postgres:hubwp001!@cp.code045.nl:54301/wphub"

# Omgevingsvariabelen voor de Worker
NODE_VERSION = "18"

[placement]
mode = "smart"

# Gebruik 'wrangler secret put AUTH_TOKEN' om de token veilig op te slaan:
# N02eunReoZnUCxIVqOlhLf8Alt1ztCUJvoMA48Im
